# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_login', models.CharField(default='', max_length=15)),
                ('acc_pass', models.CharField(default='', max_length=20)),
                ('user_name', models.CharField(default='', max_length=15)),
                ('user_email', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_header', models.CharField(default='', max_length=100)),
                ('post_text', models.TextField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
