# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160103_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_auftor_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Post'),
        ),
    ]
