# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160105_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posts_auftor_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
