# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='images_post',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
